package ngnotify.services;

import java.util.Properties;
import java.util.Vector;

import jakarta.mail.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.PasswordAuthentication;
import jakarta.mail.Session;
import jakarta.mail.Transport;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;
import jakarta.mail.Address;

public class SendEmail {
   //Configuration
   final String from = "noreply@ngnotify.com";
   final String username = "8c1b2134f153fc";// username generated by Mailtrap
   final String password = "17f189ba2664a6";// password generated by Mailtrap
   final String host = "smtp.mailtrap.io";
   final String port = "2525";
   Properties props = new Properties();

   SendEmail(){
      this.props.put("mail.smtp.auth", "true");
      this.props.put("mail.smtp.starttls.enable", "true");// it’s optional in Mailtrap
      this.props.put("mail.smtp.host", this.host);
      this.props.put("mail.smtp.port", this.port);// use one of the options in the SMTP settings tab in your Mailtrap Inbox
   }

   public void send(String[] to, String From) {
      Session session = Session.getInstance(props,
            new jakarta.mail.Authenticator() {
               protected PasswordAuthentication getPasswordAuthentication() {
                  return new PasswordAuthentication(username, password);
               }
            });
      try {
         // Create a default MimeMessage object.
         Message message = new MimeMessage(session);
         // Set From: header field
         message.setFrom(new InternetAddress(from));
         // Set To: header field
         // Put recipient's address
         Address[] toAddresses = new Address[to.length];
         for (int i = 0; i < to.length; i++) {
            toAddresses[i] = new InternetAddress(to[i]);
         }
         message.setRecipients(Message.RecipientType.TO, toAddresses);
         // Set Subject: header field
         message.setSubject("New Subscription Request From " + From);
         // Put the content of your message
         message.setText("You have a new subscription request from " + From);
         // Send message
         Transport.send(message);
         System.out.println("Sent message successfully....");
      } catch (MessagingException e) {
         throw new RuntimeException(e);
      }
   }
   public static void main(String[] args) {
      try {
         HTTP http = new HTTP();
         Vector<String> emails = http.getAdminEmails();
         String[] emailsArray = new String[emails.size()];
         emailsArray = emails.toArray(emailsArray);
         SendEmail sendEmail = new SendEmail();
         sendEmail.send(emailsArray, "test");
      } catch (Exception e) {
         System.out.println(e);
      }
      
   }
}
